In [ ]:
Data 
|
Data Collection
-- Collect the data from various sources
      - WebAPI
      - File
      - DataBase 
      - CloudStorage 
      - Streaming sources ...

-- Build Data PipeLines (ETL/ELT)
    Airflow
    PySpark
-- Data Storage / warehousing
   - HDFS , Delta Lake,Iceberg 
   - snowflake,BigQuery, Azure Synapse 
-- Data Model
-- Data Process 
-- Data - clean ->model
-- Deployment -> Docker,Kubernetets, WebFramework
---------
|
--- Continuous monitoring -- Grafana and Prometheus 
|
    project ->Deployed ->[monitor]   
                           -- cpu + memory + storage....//metrics 

In [ ]:
Python Programming
-------------------
 |-> python.org  -->downloaded --> python ->CPython 
     numpy pandas matplotlib sckiklearn ...
     pip install numpy
     pip install pandas
     ..
 |-> Anaconda - python = python + DE libs are available 

 |-> python everything is class - object design model

     native types - class
     10 Vs 10.0 Vs '10' Vs bool(10) ->True bool(0) ->False 
      [ ] ->list mutable ; ( ) ->tuple immutable ; {'Key':Value} ->dict mutable
      list of list/tuple/dict
      tuple of list/tuple/dict
      dict of list/tuple/dict
      ----    ================
      dict of list //
      set - collection of item - unique data 
      ----//union,intersection,difference,symmetric_difference 

python programming
--------------------
 |-> procedure style - direct approach style ( var = 10 
                                               def fx():
                                                   ...
                                                fx() <== direct functionCall )

 |-> Object oriented style - class<-->object
                                              obj1.var = 10
                                              obj1.fx() <== methodCall

 |->Function Style (or) expression style - Singleline 

In [1]:
import sys
print(sys.version)

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]


In [ ]:
product
  |-> productID    - 101      <== int    --->  product_id = 101 <== initialization
  |-> productName  - 'pA'     <== str 
  |-> productCost  - 19042.42  <== float 
  |-> productStatus  - True    <== bool 
Vs
product_info1 = [101,'pA',19042.42,True] <== list - Collection of different types of items
                                             |->mutable - We can add/modify/delete 

Vs 
product_info2 = (101,'pA',1904.42,True) <== tuple - Collection of different types of items
                                              |-> immutable - we can't add/modify/delete 

Vs
product_info3 = {'pid':101,'pname':'pA','pcost':1904.42,'pstatus':True} <== dict - Collection of different types of items
                                                     |-->mutable - We can add/modify/delete - w.r.t key

In [3]:
x = 45
print(type(x),x)
x = 'data'
print(type(x),x)

<class 'int'> 45
<class 'str'> data


In [4]:
product_info1 = [101,'pA',19042.42,True]
print(type(product_info1))
print(product_info1)
print(product_info1[0])
print(product_info1[1])

<class 'list'>
[101, 'pA', 19042.42, True]
101
pA


In [5]:
print(product_info1[-1])

True


In [6]:
product_info2 = (101,'pA',1904.42,True)
print(type(product_info2))
print(product_info2)
print(product_info2[0])
print(product_info2[1])
print(product_info2[-1])

<class 'tuple'>
(101, 'pA', 1904.42, True)
101
pA
True


In [7]:
def fx(a1,a2):
    print(type(a1),type(a2))

fx(10,20.4)
fx([],())
fx(True,[])
fx(4.42,{})
# we can pass any type of value as an arguments - python is dynamic type programming

<class 'int'> <class 'float'>
<class 'list'> <class 'tuple'>
<class 'bool'> <class 'list'>
<class 'float'> <class 'dict'>


In [ ]:
dict of list -> d = {'Key1':[],'Key2':[],'Key3':[]} # 1Key ->MultipleValues 

list of dict  --> L = [{},{},{},{}] # index based

In [8]:
product_info = {} # empty dict

# How to add new data to an existing dict ?
#  dictName['newKey'] = Value 

product_info['pid'] = [101,102,103]
product_info['pname'] = ['pA','pB','pC']
product_info['pcost'] = [1000,2000,3000]

product_info

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [ ]:
dict of list
each key point to /map to  - list 

In [ ]:
dict
----- // Table
           | Col1  | Col2 |
           +-------|------+
           | K1    |  V1  |  <== 
           +-------|------+
           | K2    |  V2  |  <==
           +-------|------+
           | K3    |  V3  |  <==
           +--------------+

In [10]:
# list of dict --> L = [{},{},{},{},{}]
#
# each product - individual dict 

product_info2 = [
                 {'pid':101,'pname':'pA','pcost':1000},
                 {'pid':102,'pname':'pB','pcost':2000},
                 {'pid':103,'pname':'pC','pcost':3000}
                ]

In [12]:
print(product_info2[0]['pname']) # list of dict
print(product_info2[1]['pname']) # list of dict
print(product_info2[2]['pname']) # list of dict

pA
pB
pC


In [13]:
product_info3 = {'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

print(product_info3['pname'][0])
print(product_info3['pname'][1])
print(product_info3['pname'][2])

pA
pB
pC


In [ ]:
numpy - Computation
 |->index , slicing , reshaping
 |->ufunctions

pandas - Analysis
 |-> Series 
 |-> DataFrame 

matplotlib - Visualization
 |-> plot,scatter,bar,pie,box
|
EDA

In [14]:
L = [10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [15]:
import array
arr = array.array('i',[10,20,30,40,50])
arr

array('i', [10, 20, 30, 40, 50])

In [16]:
arr.append(35)

In [17]:
arr.append(43)

In [18]:
arr

array('i', [10, 20, 30, 40, 50, 35, 43])

In [19]:
arr.append(44.5) # Vs L.append(44.5) 

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
arr+100

TypeError: can only append array (not "int") to array

In [22]:
import numpy
arr = numpy.array([10,20,30,40,50])
arr+100

array([110, 120, 130, 140, 150])

In [25]:
L=[10,20,30,40,50]
arr = numpy.array(L)
print(arr)
print(arr+100)
print(arr+198.42)

[10 20 30 40 50]
[110 120 130 140 150]
[208.42 218.42 228.42 238.42 248.42]


In [ ]:
dtype - data type
shape - dimension 

In [26]:
a1 = numpy.array([10,20,30])
a1.dtype

dtype('int64')

In [28]:
a1 = numpy.array([10,20.0,30])
print(a1)
print(a1.dtype)

[10. 20. 30.]
float64


In [29]:
a1 = numpy.array([10,20,30,True,False])
print(a1)
print(a1.dtype)

[10 20 30  1  0]
int64


In [30]:
a2 = numpy.array([True,False,True,False,False])
print(a2)
print(a2.dtype)

[ True False  True False False]
bool


In [31]:
a3 = numpy.array([10,2.0,True,'data'])
a3.dtype

dtype('<U32')

In [32]:
a1 = numpy.array([10,20,30,40,50])
a1.shape

(5,)

In [33]:
a1 = numpy.array([[10,20,30,40,50]])
a1.shape

(1, 5)

In [ ]:
(1,5) => 1Row 5Columns
(2,5) => 2Rows 5Columns
..
(569,15) ==> 569 Rows and 15Columns

In [34]:
a2 = numpy.array([[10,20,30],[40,50,60]])
print(a2.shape)

(2, 3)


In [35]:
a2.reshape(3,2) # 3rows 2columns

array([[10, 20],
       [30, 40],
       [50, 60]])

In [36]:
a2.reshape(1,6) # 1row  6columns

array([[10, 20, 30, 40, 50, 60]])