In [ ]:
Data 
|
Data Collection
-- Collect the data from various sources
      - WebAPI
      - File
      - DataBase 
      - CloudStorage 
      - Streaming sources ...

-- Build Data PipeLines (ETL/ELT)
    Airflow
    PySpark
-- Data Storage / warehousing
   - HDFS , Delta Lake,Iceberg 
   - snowflake,BigQuery, Azure Synapse 
-- Data Model
-- Data Process 
-- Data - clean ->model
-- Deployment -> Docker,Kubernetets, WebFramework
---------
|
--- Continuous monitoring -- Grafana and Prometheus 
|
    project ->Deployed ->[monitor]   
                           -- cpu + memory + storage....//metrics 

In [ ]:
Python Programming
-------------------
 |-> python.org  -->downloaded --> python ->CPython 
     numpy pandas matplotlib sckiklearn ...
     pip install numpy
     pip install pandas
     ..
 |-> Anaconda - python = python + DE libs are available 

 |-> python everything is class - object design model

     native types - class
     10 Vs 10.0 Vs '10' Vs bool(10) ->True bool(0) ->False 
      [ ] ->list mutable ; ( ) ->tuple immutable ; {'Key':Value} ->dict mutable
      list of list/tuple/dict
      tuple of list/tuple/dict
      dict of list/tuple/dict
      ----    ================
      dict of list //
      set - collection of item - unique data 
      ----//union,intersection,difference,symmetric_difference 

python programming
--------------------
 |-> procedure style - direct approach style ( var = 10 
                                               def fx():
                                                   ...
                                                fx() <== direct functionCall )

 |-> Object oriented style - class<-->object
                                              obj1.var = 10
                                              obj1.fx() <== methodCall

 |->Function Style (or) expression style - Singleline 

In [1]:
import sys
print(sys.version)

3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]


In [ ]:
product
  |-> productID    - 101      <== int    --->  product_id = 101 <== initialization
  |-> productName  - 'pA'     <== str 
  |-> productCost  - 19042.42  <== float 
  |-> productStatus  - True    <== bool 
Vs
product_info1 = [101,'pA',19042.42,True] <== list - Collection of different types of items
                                             |->mutable - We can add/modify/delete 

Vs 
product_info2 = (101,'pA',1904.42,True) <== tuple - Collection of different types of items
                                              |-> immutable - we can't add/modify/delete 

Vs
product_info3 = {'pid':101,'pname':'pA','pcost':1904.42,'pstatus':True} <== dict - Collection of different types of items
                                                     |-->mutable - We can add/modify/delete - w.r.t key

In [3]:
x = 45
print(type(x),x)
x = 'data'
print(type(x),x)

<class 'int'> 45
<class 'str'> data


In [4]:
product_info1 = [101,'pA',19042.42,True]
print(type(product_info1))
print(product_info1)
print(product_info1[0])
print(product_info1[1])

<class 'list'>
[101, 'pA', 19042.42, True]
101
pA


In [5]:
print(product_info1[-1])

True


In [6]:
product_info2 = (101,'pA',1904.42,True)
print(type(product_info2))
print(product_info2)
print(product_info2[0])
print(product_info2[1])
print(product_info2[-1])

<class 'tuple'>
(101, 'pA', 1904.42, True)
101
pA
True


In [7]:
def fx(a1,a2):
    print(type(a1),type(a2))

fx(10,20.4)
fx([],())
fx(True,[])
fx(4.42,{})
# we can pass any type of value as an arguments - python is dynamic type programming

<class 'int'> <class 'float'>
<class 'list'> <class 'tuple'>
<class 'bool'> <class 'list'>
<class 'float'> <class 'dict'>


In [ ]:
dict of list -> d = {'Key1':[],'Key2':[],'Key3':[]} # 1Key ->MultipleValues 

list of dict  --> L = [{},{},{},{}] # index based

In [8]:
product_info = {} # empty dict

# How to add new data to an existing dict ?
#  dictName['newKey'] = Value 

product_info['pid'] = [101,102,103]
product_info['pname'] = ['pA','pB','pC']
product_info['pcost'] = [1000,2000,3000]

product_info

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [ ]:
dict of list
each key point to /map to  - list 

In [ ]:
dict
----- // Table
           | Col1  | Col2 |
           +-------|------+
           | K1    |  V1  |  <== 
           +-------|------+
           | K2    |  V2  |  <==
           +-------|------+
           | K3    |  V3  |  <==
           +--------------+

In [10]:
# list of dict --> L = [{},{},{},{},{}]
#
# each product - individual dict 

product_info2 = [
                 {'pid':101,'pname':'pA','pcost':1000},
                 {'pid':102,'pname':'pB','pcost':2000},
                 {'pid':103,'pname':'pC','pcost':3000}
                ]

In [12]:
print(product_info2[0]['pname']) # list of dict
print(product_info2[1]['pname']) # list of dict
print(product_info2[2]['pname']) # list of dict

pA
pB
pC


In [13]:
product_info3 = {'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

print(product_info3['pname'][0])
print(product_info3['pname'][1])
print(product_info3['pname'][2])

pA
pB
pC


In [ ]:
numpy - Computation
 |->index , slicing , reshaping
 |->ufunctions

pandas - Analysis
 |-> Series 
 |-> DataFrame 

matplotlib - Visualization
 |-> plot,scatter,bar,pie,box
|
EDA

In [14]:
L = [10,20,30,40,50]
L+100

TypeError: can only concatenate list (not "int") to list

In [15]:
import array
arr = array.array('i',[10,20,30,40,50])
arr

array('i', [10, 20, 30, 40, 50])

In [16]:
arr.append(35)

In [17]:
arr.append(43)

In [18]:
arr

array('i', [10, 20, 30, 40, 50, 35, 43])

In [19]:
arr.append(44.5) # Vs L.append(44.5) 

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
arr+100

TypeError: can only append array (not "int") to array

In [22]:
import numpy
arr = numpy.array([10,20,30,40,50])
arr+100

array([110, 120, 130, 140, 150])

In [25]:
L=[10,20,30,40,50]
arr = numpy.array(L)
print(arr)
print(arr+100)
print(arr+198.42)

[10 20 30 40 50]
[110 120 130 140 150]
[208.42 218.42 228.42 238.42 248.42]


In [ ]:
dtype - data type
shape - dimension 

In [26]:
a1 = numpy.array([10,20,30])
a1.dtype

dtype('int64')

In [28]:
a1 = numpy.array([10,20.0,30])
print(a1)
print(a1.dtype)

[10. 20. 30.]
float64


In [29]:
a1 = numpy.array([10,20,30,True,False])
print(a1)
print(a1.dtype)

[10 20 30  1  0]
int64


In [30]:
a2 = numpy.array([True,False,True,False,False])
print(a2)
print(a2.dtype)

[ True False  True False False]
bool


In [31]:
a3 = numpy.array([10,2.0,True,'data'])
a3.dtype

dtype('<U32')

In [32]:
a1 = numpy.array([10,20,30,40,50])
a1.shape

(5,)

In [33]:
a1 = numpy.array([[10,20,30,40,50]])
a1.shape

(1, 5)

In [ ]:
(1,5) => 1Row 5Columns
(2,5) => 2Rows 5Columns
..
(569,15) ==> 569 Rows and 15Columns

In [34]:
a2 = numpy.array([[10,20,30],[40,50,60]])
print(a2.shape)

(2, 3)


In [35]:
a2.reshape(3,2) # 3rows 2columns

array([[10, 20],
       [30, 40],
       [50, 60]])

In [36]:
a2.reshape(1,6) # 1row  6columns

array([[10, 20, 30, 40, 50, 60]])

In [ ]:
## KeyConcepts - Data Lakes , DataWarehouses, Datamarts 
## data pipelines 

Data Lakes
-----------
 - centralized storage
                 |->holds raw data (unprocessed data)
 - S3,GCS
 - Schema-on-read 
 - Bigdata - ML,AI
 - IoT,media files,storing logs 

Data Warehouse 
----------------
 - Centraized storage 
                |-> cleaned data --- analytics - ML

    - Stores structed data only 
    - snowflake , bigquery
    - Dashboard , regression

Data Marts
-------------
   - Subset of datawarehouse 
       |->ie., Cleaned data
       |->focus here is apply this data - specific domain(Sales,Finance,...)
    - Smaller size Vs Warehouse 
      ------------

[ DataSource ]
   |->API
   |->File
   |->Appln generated 
        ...
   |------------------------[Data Lake] -->[Data warehouse] --->[Data Marts] -->[Appln - Dashboard/report]
                                            ================================= 

Extract
Load
Transform
Validate
Store
------//chain - pipeline 
|
Orchestration 
 - Workflow + schedule + monitor pipeline 
########
WebContent
  |--> JSON format - data response
           Vs
  |--> WebPage -  <html>.{{data}}.</html>
                 =======================
                     |->webscrabing - bs4

In [ ]:
requests 
  - get method - Get URL Content 
bs4
  - webscraping 

-----------------
To download any webContent
Step 1 : import requests module
Step 2:  requests.get(URL) ->status_Code - 200 # OK
Step 3:  requests.headers //dict -> URL Header information 
Step 4:  Application json data --> go to json 
         WebPage --->go to webscraping use bs4 module


In [37]:
import requests
requests.get('https://www.google.com')

<Response [200]>

In [39]:
r = requests.get('https://www.google.com')
r.status_code

200

In [40]:
r.headers

{'Date': 'Mon, 01 Dec 2025 09:26:29 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Content-Security-Policy-Report-Only': "object-src 'none';base-uri 'self';script-src 'nonce-AacJWW_d1GchcvInNj7g0g' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp", 'Accept-CH': 'Sec-CH-Prefers-Color-Scheme', 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': 'AEC=AaJma5t8SfG3Ab7ScpLzHQIg_YJ77miW0N5CibC52d2JXwK03ApXNVd2wQ; expires=Sat, 30-May-2026 09:26:29 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax, NID=526=iZXXe7HugV8NBDBakQENsRWYMZpzcYTtjc4wzb1GMq2GcWmuJXWUCleM-ujtv2DUFkgmSDGHg3xn-YHh8m7r3KoqnBpS3Uv4_FoLo4XYqBh7Yl9YZdEUJJFqXSS_Hyw0Uh0x_yI-_0U-0xbi_K_9hUJw3I9wRGIaOoxMOsUJq1o_iOdpR_n3Hz07g1Vx-ekBbnp33_

In [41]:
URL = 'https://jsonplaceholder.typicode.com/users/1'

r1 = requests.get(URL)
r1.status_code

200

In [42]:
r1.headers

{'Date': 'Mon, 01 Dec 2025 09:33:29 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'etag': 'W/"1fd-+2Y3G3w049iSZtw5t1mzSnunngE"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=nKCeMC%2BDU3lDhUAGS9nkSHtX7jLlQqRr4etGxlGREYI%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1764518428"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=nKCeMC%2BDU3lDhUAGS9nkSHtX7jLlQqRr4etGxlGREYI%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1764518428"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-

In [44]:
print(r.headers['Content-Type'])
print('')
print(r1.headers['Content-Type'])

text/html; charset=ISO-8859-1

application/json; charset=utf-8


In [45]:
web_page = r.text # download web content to local variable
print(type(web_page),len(web_page))

<class 'str'> 20077


In [46]:
## For testing
with open("test1.html","w") as wobj:
    wobj.write(web_page)

In [49]:
'text/html' in r.headers['Content-Type']

True

In [50]:
'application/json' in r.headers['Content-Type']

False

In [57]:
# To download WebContent
import requests
URL = 'https://www.google.com'
r = requests.get(URL)
if(r.status_code != 200):
    print("Download is failed")

if('text/html' in r.headers['Content-Type']):
    web_data = r.text
    '''do webscraping'''

In [58]:
web_data = r.text

In [60]:
product_info3 = {'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

print(type(product_info3))

<class 'dict'>


In [61]:
import json
json.dumps(product_info3)

'{"pid": [101, 102, 103], "pname": ["pA", "pB", "pC"], "pcost": [1000, 2000, 3000]}'

In [62]:
json.dumps(product_info3,indent=3)

'{\n   "pid": [\n      101,\n      102,\n      103\n   ],\n   "pname": [\n      "pA",\n      "pB",\n      "pC"\n   ],\n   "pcost": [\n      1000,\n      2000,\n      3000\n   ]\n}'

In [64]:
# Convert from python ->json
## ---------------------------
print(json.dumps(product_info3))
print('')
print(json.dumps(product_info3,indent=3))

{"pid": [101, 102, 103], "pname": ["pA", "pB", "pC"], "pcost": [1000, 2000, 3000]}

{
   "pid": [
      101,
      102,
      103
   ],
   "pname": [
      "pA",
      "pB",
      "pC"
   ],
   "pcost": [
      1000,
      2000,
      3000
   ]
}


In [65]:
json_data = json.dumps(product_info3,indent=3)

In [66]:
python_data = json.loads(json_data)
print(type(python_data))

<class 'dict'>


In [67]:
python_data

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [ ]:
####

In [ ]:
Web scraping - Extracting data from HTML and XML Pages
------------
 |-> bs4 - BeautifulSoup4 
     |->  we will use dictionary operations
     |->  find tags 
     |->  search by class,ID
     |->  extract text
     |->  navigate elements
             |-> parent - child
             |-> sibblings

<html>
<head>
<title>Welcome</title>
<body>
<p>
 <a class="ID" href="URL" color="green">
    ---------- =========  ------------ //apply dict logic
  
</p>
 </body>
 </head>
</html>


Step-1:  import bs4
Step-2:  bs4.BeautifulSoup //className
                |
                |->constructor argument is WebContent 
         soup_obj = bs4.BeautifulSoup("WebContent")
         soup_obj.<htmlTag> ->Get the data - 1st matched data
             <or>
         soup_obj.find(<htmlTag>) ->Get the data - 1st matched data

         soup_obj.find_all(<htmlTag>) ->List of data 

step -3 : dict of list format ==>east to convert to DataFrame - for analysis 

In [69]:
import bs4
soup_obj = bs4.BeautifulSoup(web_data)

In [70]:
soup_obj.title

<title>Google</title>

In [73]:
soup_obj.title.string

'Google'

In [74]:
soup_obj.p

<p style="font-size:8pt;color:#636363">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>

In [75]:
soup_obj.find('p') # same as soup_obj.p

<p style="font-size:8pt;color:#636363">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>

In [76]:
soup_obj.find_all('p') # Find all the Tags 

[<p style="font-size:8pt;color:#636363">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>]

In [78]:
soup_obj.find(id="main-content")

In [79]:
soup_obj.find('p').get_text()

'© 2025 - Privacy - Terms'

In [80]:
soup_obj.find_all('p')

[<p style="font-size:8pt;color:#636363">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p>]

In [82]:
soup_obj.find_all('p')[0]['style'] # dict style 

'font-size:8pt;color:#636363'

In [83]:
soup_obj.find_all('p')[0].get('style') # dict style  - same as soup_obj.find_all('p')

'font-size:8pt;color:#636363'

In [87]:
d={'K1':'V1'}
d['K1']
d.get('K1')
print(d.get('K2'))

None


In [98]:
print(soup_obj.find('a'))
print('')
print(soup_obj.find('a').get('href'))

<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>

https://www.google.com/imghp?hl=en&tab=wi


In [102]:
## Extract list pf href links from google.com
for var in soup_obj.find_all('a'):
    print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
/preferences?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
/advanced_search?hl=en-IN&authuser=0
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAY
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAc
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAg
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrA

In [103]:
URLs = []
for var in soup_obj.find_all('a'):
    URLs.append(var) #print(var.get('href'))


In [104]:
URLs

[<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>,
 <a class="gb1" href="https://maps.google.co.in/maps?hl=en&amp;tab=wl">Maps</a>,
 <a class="gb1" href="https://play.google.com/?hl=en&amp;tab=w8">Play</a>,
 <a class="gb1" href="https://www.youtube.com/?tab=w1">YouTube</a>,
 <a class="gb1" href="https://news.google.com/?tab=wn">News</a>,
 <a class="gb1" href="https://mail.google.com/mail/?tab=wm">Gmail</a>,
 <a class="gb1" href="https://drive.google.com/?tab=wo">Drive</a>,
 <a class="gb1" href="https://www.google.co.in/intl/en/about/products?tab=wh" style="text-decoration:none"><u>More</u> »</a>,
 <a class="gb4" href="http://www.google.co.in/history/optout?hl=en">Web History</a>,
 <a class="gb4" href="/preferences?hl=en">Settings</a>,
 <a class="gb4" href="https://accounts.google.com/ServiceLogin?hl=en&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAAQ" id="gb_70" target="_top">Sign in</a>,
 <a href="/advanced_search?hl=en-IN&amp;authuser=

In [105]:
d={}
d['Google']=URLs
d

{'Google': [<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>,
  <a class="gb1" href="https://maps.google.co.in/maps?hl=en&amp;tab=wl">Maps</a>,
  <a class="gb1" href="https://play.google.com/?hl=en&amp;tab=w8">Play</a>,
  <a class="gb1" href="https://www.youtube.com/?tab=w1">YouTube</a>,
  <a class="gb1" href="https://news.google.com/?tab=wn">News</a>,
  <a class="gb1" href="https://mail.google.com/mail/?tab=wm">Gmail</a>,
  <a class="gb1" href="https://drive.google.com/?tab=wo">Drive</a>,
  <a class="gb1" href="https://www.google.co.in/intl/en/about/products?tab=wh" style="text-decoration:none"><u>More</u> »</a>,
  <a class="gb4" href="http://www.google.co.in/history/optout?hl=en">Web History</a>,
  <a class="gb4" href="/preferences?hl=en">Settings</a>,
  <a class="gb4" href="https://accounts.google.com/ServiceLogin?hl=en&amp;passive=true&amp;continue=https://www.google.com/&amp;ec=GAZAAQ" id="gb_70" target="_top">Sign in</a>,
  <a href="/advanced_search?

In [106]:
import re
# Regular Expression
# re.search('pattern',inputdata) -> obj ->OK
#                                |->None -> Not-Matched


In [109]:
for var in soup_obj.find_all('a'):
    print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
/preferences?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
/advanced_search?hl=en-IN&authuser=0
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAY
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAc
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAg
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrA

In [110]:
for var in soup_obj.find_all('a'):
    if(re.search('^http',var.get('href'))):
        print(var.get('href'))

https://www.google.com/imghp?hl=en&tab=wi
https://maps.google.co.in/maps?hl=en&tab=wl
https://play.google.com/?hl=en&tab=w8
https://www.youtube.com/?tab=w1
https://news.google.com/?tab=wn
https://mail.google.com/mail/?tab=wm
https://drive.google.com/?tab=wo
https://www.google.co.in/intl/en/about/products?tab=wh
http://www.google.co.in/history/optout?hl=en
https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https://www.google.com/&ec=GAZAAQ
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=hi&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAY
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=bn&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAc
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=te&source=homepage&sa=X&ved=0ahUKEwio8IjOjZyRAxVbrJUCHeG7BKUQ2ZgBCAg
https://www.google.com/setprefs?sig=0_XLw_S19WkPHIAMvHuz_hrAc3eF8%3D&hl=mr&source=homepage&sa=X&ved=0ahUKEwio8IjOjZy

In [112]:
Google_URLs = []
for var in soup_obj.find_all('a'):
    if(re.search('^http',var.get('href'))):
        Google_URLs.append(var.get('href'))

In [113]:
len(Google_URLs)

21

In [116]:
##Navigate parent element

soup_obj.title

<title>Google</title>

In [118]:
soup_obj.title.parent
soup_obj.p.parent

<span id="footer"><div style="font-size:10pt"><div id="WqQANb" style="margin:19px auto;text-align:center"><a href="/intl/en/ads/">Advertising</a><a href="http://www.google.co.in/services/">Business Solutions</a><a href="/intl/en/about.html">About Google</a><a href="https://www.google.com/setprefdomain?prefdom=IN&amp;prev=https://www.google.co.in/&amp;sig=K_PrTwa0aSdMic_Gf425CExpeE20o%3D">Google.co.in</a></div></div><p style="font-size:8pt;color:#636363">© 2025 - <a href="/intl/en/policies/privacy/">Privacy</a> - <a href="/intl/en/policies/terms/">Terms</a></p></span>

In [120]:
soup_obj.p.parent.strings

<generator object Tag._all_strings at 0x0000024EADB68310>

In [ ]:
generator 
 |->function - returns an iterator (address)

In [121]:
def myf1():
    yield 10
    yield "STDOUT","STDERR"
    yield "D1","D2","D3"
    yield "D1",["D2","D3","D4"],["D5","D6"]

In [122]:
myf1()

<generator object myf1 at 0x0000024EB0AF71C0>

In [ ]:
# typecast to list ->(1)
#  <or>
# for loop ->(2)
#  <or>
# next(genObj) ->(3)

In [123]:
list(myf1())

[10,
 ('STDOUT', 'STDERR'),
 ('D1', 'D2', 'D3'),
 ('D1', ['D2', 'D3', 'D4'], ['D5', 'D6'])]

In [124]:
for var in myf1():
    print(var)

10
('STDOUT', 'STDERR')
('D1', 'D2', 'D3')
('D1', ['D2', 'D3', 'D4'], ['D5', 'D6'])


In [125]:
soup_obj.p.parent.strings

<generator object Tag._all_strings at 0x0000024EAEC0B4C0>

In [126]:
list(soup_obj.p.parent.strings)

['Advertising',
 'Business Solutions',
 'About Google',
 'Google.co.in',
 '© 2025 - ',
 'Privacy',
 ' - ',
 'Terms']

In [129]:
soup_obj.body.children

In [131]:
#list(soup_obj.body.children) # same like generator logic

In [132]:
soup_obj.h4

In [133]:
soup_obj.find('a')

<a class="gb1" href="https://www.google.com/imghp?hl=en&amp;tab=wi">Images</a>

In [137]:
soup_obj.find('a').get("class")

['gb1']

In [ ]:
https://webscraper.io/test-sites/e-commerce/static/computers/laptops    

In [151]:
URL = 'https://webscraper.io/test-sites/e-commerce/static/computers/laptops'

In [152]:
response = requests.get(URL)
soup_obj = bs4.BeautifulSoup(response.text)

In [153]:
products = soup_obj.find_all("div",class_="thumbnail")

In [154]:
import csv

In [155]:
with open("products.csv","w", newline="",encoding="utf-8") as wobj:
    writer = csv.writer(wobj)
    writer.writerow(["Product Name","Price","Description"])

    for item in products:
        name = item.find("a",class_="title")
        price = item.find("a",class_="pull-right-price")
        description = item.find("a",class_="description")

        print(name,price)
        writer.writerow([name,price,description])

    

<a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
						Packard 255 G2
					</a> None
<a class="title" href="/test-sites/e-commerce/static/product/32" itemprop="name" title="Aspire E1-510">
						Aspire E1-510
					</a> None
<a class="title" href="/test-sites/e-commerce/static/product/33" itemprop="name" title="ThinkPad T540p">
						ThinkPad T540p
					</a> None
<a class="title" href="/test-sites/e-commerce/static/product/34" itemprop="name" title="ProBook">
						ProBook
					</a> None
<a class="title" href="/test-sites/e-commerce/static/product/35" itemprop="name" title="ThinkPad X240">
						ThinkPad X240
					</a> None
<a class="title" href="/test-sites/e-commerce/static/product/36" itemprop="name" title="Aspire E1-572G">
						Aspire E1-572G
					</a> None


In [156]:
products

[<div class="card thumbnail" itemscope="" itemtype="https://schema.org/Product">
 <div class="product-wrapper card-body">
 <img alt="item" class="img-fluid card-img-top image img-responsive" itemprop="image" src="/images/test-sites/e-commerce/items/cart2.png"/>
 <div class="caption">
 <h4 class="price float-end card-title pull-right" itemprop="offers" itemscope="" itemtype="https://schema.org/Offer">
 <span itemprop="price">$416.99</span>
 <meta content="USD" itemprop="priceCurrency"/>
 </h4>
 <h4>
 <a class="title" href="/test-sites/e-commerce/static/product/31" itemprop="name" title="Packard 255 G2">
 						Packard 255 G2
 					</a>
 </h4>
 <p class="description card-text" itemprop="description">15.6", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows 8.1</p>
 </div>
 <div class="ratings" itemprop="aggregateRating" itemscope="" itemtype="https://schema.org/AggregateRating">
 <p class="review-count float-end">
 <span itemprop="reviewCount">2</span> reviews
 				</p>
 <p data-rating="2">
 <span 

In [ ]:
## pandas 
    |-> data analysis - processing (load ->cleaning)

    |->Series |->DataFrame                                              

In [157]:
import pandas as pd
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

In [158]:
pd.DataFrame([10,20,30])

0
0  10
1  20
2  30

In [159]:
products={}
products['pid']=[101,102,103]
products['pname']=['pA','pB','pC']
products['pcost']=[1000,2000,3000]
products

{'pid': [101, 102, 103],
 'pname': ['pA', 'pB', 'pC'],
 'pcost': [1000, 2000, 3000]}

In [160]:
pd.DataFrame(products)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000

In [161]:
df1 = pd.DataFrame(products)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     3 non-null      int64 
 1   pname   3 non-null      object
 2   pcost   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes


In [162]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [163]:
df1.columns

Index(['pid', 'pname', 'pcost'], dtype='object')

In [164]:
df1['pname']

0    pA
1    pB
2    pC
Name: pname, dtype: object

In [165]:
df1['pcost']

0    1000
1    2000
2    3000
Name: pcost, dtype: int64

In [166]:
# row based access
df1.loc[1]

pid       102
pname      pB
pcost    2000
Name: 1, dtype: object

In [167]:
df1.loc[1]['pname']

'pB'

In [168]:
df1.loc[2]['pname']

'pC'

In [169]:
df1.loc[2][['pname','pcost']]

pname      pC
pcost    3000
Name: 2, dtype: object

In [170]:
products={}
products['pid']=[101,102,103]
products['pname']=['pA','pB','pC']
products['pcost']=[1000,2000,3000]

products['pid'].append(104)
products['pname'].append('pD')
products['pcost'].append(4000)


products['pid'].append(105)
products['pname'].append('pE')
products['pcost'].append(5000)

products['pid'].append(106)
products['pname'].append('pF')
products['pcost'].append(6000)


products['pid'].append(107)
products['pname'].append('pG')
products['pcost'].append(7000)

products['pid'].append(108)
products['pname'].append('pF')
products['pcost'].append(8000)
products

{'pid': [101, 102, 103, 104, 105, 106, 107, 108],
 'pname': ['pA', 'pB', 'pC', 'pD', 'pE', 'pF', 'pG', 'pF'],
 'pcost': [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000]}

In [171]:
df2 = pd.DataFrame(products)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   pid     8 non-null      int64 
 1   pname   8 non-null      object
 2   pcost   8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes


In [172]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [173]:
df2.loc[2]

pid       103
pname      pC
pcost    3000
Name: 2, dtype: object

In [174]:
df2.loc[2:] # from 2nd row to list of all - slicing

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [175]:
df2.loc[2:4] # from 2nd row to 4th row

pid pname  pcost
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000

In [176]:
df2.loc[2:4][['pname','pcost']]

pname  pcost
2    pC   3000
3    pD   4000
4    pE   5000

In [178]:
df2['pcost'] >4500

0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
Name: pcost, dtype: bool

In [179]:
df2[df2['pcost'] >4500] # boolean index

pid pname  pcost
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [183]:
[(df2['pcost'] >3500) & (df2['pcost'] < 5000)]

[0    False
 1    False
 2    False
 3     True
 4    False
 5    False
 6    False
 7    False
 Name: pcost, dtype: bool]

In [185]:
df2[(df2['pcost'] >3500) & (df2['pcost'] < 5000)]

pid pname  pcost
3  104    pD   4000

In [ ]:
# In pandas df - mutable - inplace=True -- modified input dataframe

In [186]:
# To delete a particular row/record
# df.drop(rowIndex)
df2.drop(3)

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [187]:
df2

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
3  104    pD   4000
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [188]:
df3 = df2.drop(3)
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
4  105    pE   5000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [189]:
# In pandas df - mutable - inplace=True -- modified input dataframe
# df.method(.. inplace=True) ->None but original dataframe(or) input dataframe will get updated 
df3.drop(4,inplace=True)

In [190]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [191]:
# To delete the columns
df3.drop(columns="pname")

pid  pcost
0  101   1000
1  102   2000
2  103   3000
5  106   6000
6  107   7000
7  108   8000

In [192]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [ ]:
# df3.drop(columns="pname") 
#
#  Vs
# df3.drop(columns=['pname','pcost'])

In [193]:
df3.drop(columns=['pname','pcost'])

pid
0  101
1  102
2  103
5  106
6  107
7  108

In [194]:
df3

pid pname  pcost
0  101    pA   1000
1  102    pB   2000
2  103    pC   3000
5  106    pF   6000
6  107    pG   7000
7  108    pF   8000

In [195]:
df3.drop(columns=['pname','pcost'],inplace=True)

In [196]:
df3

pid
0  101
1  102
2  103
5  106
6  107
7  108

In [ ]:
###########  End of the day1 ##########